# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040452038db3d98c50b59713c04e34e61b8874a40e1b9627cf606759e50f3250a2e1fc08d30a554e5eee67d842f63df51f9fd71fb3f792350eb8d546e82c03aa

test:
  secret_key_base: 530643e476cbb0d3d7d9ea8ee0e08531cc80c4a5759e2b5fddaed4115b0c1b97f3ec15793d23c95b1e6e6dd27a04bf1945d2ea6ad88b71ff8b37bb526b2c3312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: asdasdasdasflmgsdfaksejaklqiwhenajksdbaihwbdaksdnaskdbasiudbeawejdnaiu2h4298heunaiwdw
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
